# These are supported funding model platforms

github:  [ceeanproject]
patreon:[ceeanproject] 
open_collective:[ ceeanproject]
ko_fi: [ceeanproject]
tidelift:[ceeanproject]
community_bridge:[ceeanproject]
liberapay:[ceeanproject] 
issuehunt:[ceeanproject] 
otechie:[ceeanproject] 
lfx_crowdfunding:[ceeanproject 
polar:[ceeanproject]
custom:[ceeanproject] 
