 These are supported funding model platforms

github:  Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
Google:[CEEANPROJECT 
ko_fi:[mamidze]
Meta:[mamidze]
Clojure:[CEEANPROJECT]
Apereo:[CEEANPROJECT]
Canonical:[CEEANPROJECT]
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
Salesforce:[CEEANPROJECT]
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
